In [2]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [20]:
url = "https://www.pro-football-reference.com/teams/"

In [21]:
team_ids = pd.read_csv("ORIE4741proj/Datasets/nfl_teams_with_spaces.csv")

In [54]:
##finding team abbreviations used by PFR
# url = 'https://www.pro-football-reference.com/years/2019/'
# reqs = requests.get(url) 
# soup = BeautifulSoup(reqs.text, 'html.parser') 
  
# urls = [] 
# for link in soup.find_all('a'): 
#     print(link.get('href'))

In [22]:
# team_ids
# teams = team_ids["Abbreviation"]
teams = ['crd', 'atl', 'rav', 'buf', 'car', 'chi', 'cin', 'cle', 'dal', 'den', 'det', 'gnb', 'htx', 'clt',  
               'jax', 'kan', 'mia', 'min', 'nwe', 'nor', 'nyg', 'nyj', 'rai', 'phi', 'pit', 'sdg', 'sfo', 'sea',
                'ram', 'tam', 'oti', 'was']

In [32]:
def process(data, team):
    assert 17 <= data.shape[0] <= 22
    assert data.shape[1] == 25 #confirm we are getting the right table
    data.insert(0, "Team", (teams.index(team) + 1)*np.ones(data.shape[0]))
    return data

In [30]:
#returns a dataframe containing all game data from the given year from Pro Football Reference
#with team and year identifiers added
def get_year_data(year):
    team = teams[0]
    year_data = pd.read_html(url + team + "/" + str(year) + ".htm")[1] #take in the first team so we can append in the loop
    year_data = process(year_data, team)
#     assert 17 <= year_data.shape[0] <= 22
#     assert year_data.shape[1] == 25 #confirm we are getting the right table
#     year_data.insert(0, "Team", (teams.index(team) + 1)*np.ones(year_data.shape[0]))
    
    for team in teams[1:]:
        team_data = pd.read_html(url + team + "/" + str(year) + ".htm")[1]  #gets the table from the URL
#         assert 16 <= team_data.shape[0] <= 22   #16 is the minimum bc week 1 bye is eliminated from table, see 2017 dolphins
#         assert team_data.shape[1] == 25 #confirm we are getting the right table
#         team_data.insert(0, "Team", (teams.index(team) + 1)*np.ones(team_data.shape[0]))   #inserts team ID
        team_data = process(team_data, team)
        year_data = year_data.append(team_data)    #appends to year dataset
        print(str(year) + ' ' + team)   #for debugging purposes
    year_data.insert(0, "Year", year*np.ones(year_data.shape[0]))    #adds year ID
    return year_data

In [33]:
#concatenates datasets year over year
first_year = 2010
last_year = 2012

all_data = get_year_data(last_year)
for i in range(last_year-1, first_year-1, -1):  
    all_data = all_data.append(get_year_data(i))

2012 atl
2012 rav
2012 buf
2012 car
2012 chi
2012 cin
2012 cle
2012 dal
2012 den
2012 det
2012 gnb
2012 htx
2012 clt
2012 jax
2012 kan
2012 mia
2012 min
2012 nwe
2012 nor
2012 nyg
2012 nyj
2012 rai
2012 phi
2012 pit
2012 sdg
2012 sfo
2012 sea
2012 ram
2012 tam
2012 oti
2012 was
2011 atl
2011 rav
2011 buf
2011 car
2011 chi
2011 cin
2011 cle
2011 dal
2011 den
2011 det
2011 gnb
2011 htx
2011 clt
2011 jax
2011 kan
2011 mia
2011 min
2011 nwe
2011 nor
2011 nyg
2011 nyj
2011 rai
2011 phi
2011 pit
2011 sdg
2011 sfo
2011 sea
2011 ram
2011 tam
2011 oti
2011 was
2010 atl
2010 rav
2010 buf
2010 car
2010 chi
2010 cin
2010 cle
2010 dal
2010 den
2010 det
2010 gnb
2010 htx
2010 clt
2010 jax
2010 kan
2010 mia
2010 min
2010 nwe
2010 nor
2010 nyg
2010 nyj
2010 rai
2010 phi
2010 pit
2010 sdg
2010 sfo
2010 sea
2010 ram
2010 tam
2010 oti
2010 was

In [47]:
all_data.to_csv('2010_thru_2012.csv', index = False)

In [49]:
full = old.append(new)
full

                   Year               Team Unnamed: 0_level_0  \
     Unnamed: 0_level_1 Unnamed: 1_level_1               Week
0                2019.0                1.0                  1
1                2019.0                1.0                  2
2                2019.0                1.0                  3
3                2019.0                1.0                  4
4                2019.0                1.0                  5
...                 ...                ...                ...
1729             2010.0               32.0                 13
1730             2010.0               32.0                 14
1731             2010.0               32.0                 15
1732             2010.0               32.0                 16
1733             2010.0               32.0                 17

     Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                    Day               Date Unnamed: 3_level_1
0                   Sun        September 8          4:25PM ET
1                   Sun       September 15          1:00PM ET
2                   Sun       September 22          4:05PM ET
3                   Sun       September 29          4:05PM ET
4                   Sun          October 6          1:00PM ET
...                 ...                ...                ...
1729                Sun         December 5          1:02PM ET
1730                Sun        December 12          1:03PM ET
1731                Sun        December 19          1:03PM ET
1732                Sun        December 26          1:03PM ET
1733                Sun          January 2          4:16PM ET

     Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0  \
     Unnamed: 4_level_1 Unnamed: 5_level_1                 OT
0              boxscore                  T                 OT
1              boxscore                  L                NaN
2              boxscore                  L                NaN
3              boxscore                  L                NaN
4              boxscore                  W                NaN
...                 ...                ...                ...
1729           boxscore                  L                NaN
1730           boxscore                  L                NaN
1731           boxscore                  L                NaN
1732           boxscore                  W                 OT
1733           boxscore                  L                NaN

     Unnamed: 7_level_0 Unnamed: 8_level_0    Unnamed: 9_level_0 Score        \
                    Rec Unnamed: 8_level_1                   Opp    Tm   Opp
0                 0-0-1                NaN         Detroit Lions  27.0  27.0
1                 0-1-1                  @      Baltimore Ravens  17.0  23.0
2                 0-2-1                NaN     Carolina Panthers  20.0  38.0
3                 0-3-1                NaN      Seattle Seahawks  10.0  27.0
4                 1-3-1                  @    Cincinnati Bengals  26.0  23.0
...                 ...                ...                   ...   ...   ...
1729                5-7                  @       New York Giants   7.0  31.0
1730                5-8                NaN  Tampa Bay Buccaneers  16.0  17.0
1731                5-9                  @        Dallas Cowboys  30.0  33.0
1732                6-9                  @  Jacksonville Jaguars  20.0  17.0
1733               6-10                NaN       New York Giants  14.0  17.0

     Offense                           Defense                            \
        1stD  TotYd  PassY  RushY   TO    1stD  TotYd  PassY  RushY   TO
0       21.0  387.0  275.0  112.0  1.0    23.0  477.0  361.0  116.0  2.0
1       15.0  349.0  329.0   20.0  NaN    26.0  440.0  258.0  182.0  NaN
2       21.0  248.0  127.0  121.0  2.0    21.0  413.0  240.0  173.0  1.0
3       20.0  321.0  206.0  115.0  1.0    21.0  340.0  225.0  115.0  NaN
4       26.0  514.0  248.0  266.0  NaN    21.0  370.0  262.0  108.0  NaN
...      ...    ...    ...    ...  ...     ...    ...    ...    ...  ...
1729    19.0  338.0  264.0   74.0  6.0    22.0  358.0  161.0  197.0  1.0
1730    22.0  399.0  211.0  188.0  1.0    15.0  365.0  262.0  103.0  2.0
1731    23.0  341.0  286.0   55.0  3.0    25.0  434.0  300.0  134.0  NaN
1732    15.0  251.0  172.0   79.0  1.0    15.0  336.0  258.0   78.0  2.0
1733    20.0  385.0  318.0   67.0  4.0    14.0  325.0  243.0   82.0  1.0

     Expected Points
             Offense Defense Sp. Tms
0              -3.50   -7.02    9.80
1               4.48  -11.60   -4.18
2              -3.15  -19.08    3.46
3              -0.78  -10.61   -2.81
4              21.22   -9.27   -8.95
...              ...     ...     ...
1729          -17.38   -4.40   -1.49
1730           10.79    1.13  -14.62
1731            7.69  -12.15   -0.55
1732          -10.82   10.87    4.68
1733           -9.54    4.38    0.99

[5778 rows x 27 columns]

In [50]:
# old = pd.read_csv('2013_thru_2019.csv', header = [0,1])
full.to_csv('2010_thru_2019.csv', index = False)

In [48]:
new = pd.read_csv('2010_thru_2012.csv', header = [0,1])

In [156]:
# team_data = pd.read_html(url + teams[16] + "/" + '2017' + ".htm")[1]  #gets the table from the URL

In [166]:
# team_data.shape

In [165]:
#debugging

# year = 2017
# for team in teams[1:]:
#     team_data = pd.read_html(url + team + "/" + str(year) + ".htm")[1]  #gets the table from the URL
#     assert 16 <= team_data.shape[0] <= 21
#     assert team_data.shape[1] == 25 #confirm we are getting the right table
#     team_data.insert(0, "Team", (teams.index(team) + 1)*np.ones(team_data.shape[0]))
#     print(str(year) + ' ' + team + ' ' + i)

In [3]:
url_p = "https://www.pro-football-reference.com/teams/buf/2018.htm"
site = pd.read_html(url_p)

In [7]:
games = site[1]

In [13]:
games

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                 Week                Day               Date
0                   1                Sun        September 9
1                   2                Sun       September 16
2                   3                Sun       September 23
3                   4                Sun       September 30
4                   5                Sun          October 7
5                   6                Sun         October 14
6                   7                Sun         October 21
7                   8                Mon         October 29
8                   9                Sun         November 4
9                  10                Sun        November 11
10                 11                NaN                NaN
11                 12                Sun        November 25
12                 13                Sun         December 2
13                 14                Sun         December 9
14                 15                Sun        December 16
15                 16                Sun        December 23
16                 17                Sun        December 30

   Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
   Unnamed: 3_level_1 Unnamed: 4_level_1 Unnamed: 5_level_1
0           1:00PM ET           boxscore                  L
1           1:00PM ET           boxscore                  L
2           1:00PM ET           boxscore                  W
3           1:00PM ET           boxscore                  L
4           1:00PM ET           boxscore                  W
5           1:00PM ET           boxscore                  L
6           1:00PM ET           boxscore                  L
7           8:15PM ET           boxscore                  L
8           1:00PM ET           boxscore                  L
9           1:00PM ET           boxscore                  W
10                NaN                NaN                NaN
11          1:00PM ET           boxscore                  W
12          1:00PM ET           boxscore                  L
13          1:00PM ET           boxscore                  L
14          1:00PM ET           boxscore                  W
15          1:00PM ET           boxscore                  L
16          1:00PM ET           boxscore                  W

   Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0  \
                   OT                Rec Unnamed: 8_level_1
0                 NaN                0-1                  @
1                 NaN                0-2                NaN
2                 NaN                1-2                  @
3                 NaN                1-3                  @
4                 NaN                2-3                NaN
5                 NaN                2-4                  @
6                 NaN                2-5                  @
7                 NaN                2-6                NaN
8                 NaN                2-7                NaN
9                 NaN                3-7                  @
10                NaN                NaN                NaN
11                NaN                4-7                NaN
12                NaN                4-8                  @
13                NaN                4-9                NaN
14                NaN                5-9                NaN
15                NaN               5-10                  @
16                NaN               6-10                NaN

      Unnamed: 9_level_0 Score       Offense                            \
                     Opp    Tm   Opp    1stD  TotYd  PassY  RushY   TO
0       Baltimore Ravens   3.0  47.0    10.0  153.0   70.0   83.0  2.0
1   Los Angeles Chargers  20.0  31.0    17.0  293.0  209.0   84.0  2.0
2      Minnesota Vikings  27.0   6.0    16.0  292.0  164.0  128.0  NaN
3      Green Bay Packers   0.0  22.0    11.0  145.0   87.0   58.0  3.0
4       Tennessee Titans  13.0  12.0    18.0  223.0   79.0  144.0  1.0
5         Houston Texans  13.0  20.0    12.0  229.0  129.0  100.0  3.0
6     Indianapolis Colts   5.0  37.0    15.0  303.0  168.0  135.0  5.0
7   New England Patriots   6.0  25.0    16.0  333.0  287.0   46.0  2.0
8          Chicago Bears   9.0  41.0    22.0  264.0  166.0   98.0  4.0
9          New York Jets  41.0  10.0    23.0  451.0  239.0  212.0  NaN
10              Bye Week   NaN   NaN     NaN    NaN    NaN    NaN  NaN
11  Jacksonville Jaguars  24.0  21.0    18.0  327.0  160.0  167.0  NaN
12        Miami Dolphins  17.0  21.0    24.0  415.0  217.0  198.0  3.0
13         New York Jets  23.0  27.0    24.0  368.0  192.0  176.0  3.0
14         Detroit Lions  14.0  13.0    20.0  312.0  195.0  117.0  NaN
15  New England Patriots  12.0  24.0    14.0  289.0  217.0   72.0  3.0
16        Miami Dolphins  42.0  17.0    23.0  381.0  215.0  166.0  1.0

   Defense                           Expected Points
      1stD  TotYd  PassY  RushY   TO         Offense Defense Sp. Tms
0     26.0  369.0  252.0  117.0  1.0          -28.71   -7.23   -2.33
1     21.0  349.0  240.0  109.0  NaN           -1.04  -14.41   -0.51
2     21.0  292.0  278.0   14.0  3.0            3.26   10.71    3.62
3     22.0  423.0  282.0  141.0  2.0          -21.05   -2.71    7.70
4     15.0  221.0  121.0  100.0  3.0           -2.83   12.22   -8.39
5     15.0  216.0  142.0   74.0  3.0          -17.49   12.36   -6.15
6     22.0  376.0  156.0  220.0  NaN          -22.35  -22.28    7.56
7     22.0  387.0  311.0   76.0  NaN          -20.65   -3.65    6.52
8     11.0  190.0  126.0   64.0  1.0          -29.93    2.58   -2.21
9     12.0  199.0  116.0   83.0  2.0           16.35   15.96    5.86
10     NaN    NaN    NaN    NaN  NaN             NaN     NaN     NaN
11    25.0  333.0  107.0  226.0  2.0            7.07    0.38   -2.11
12    15.0  175.0  115.0   60.0  1.0           10.93   -0.01   -9.78
13    15.0  248.0  170.0   78.0  2.0            6.81   -4.74   -5.69
14    14.0  313.0  208.0  105.0  NaN            6.53   -4.83   -0.58
15    20.0  390.0  117.0  273.0  3.0          -16.90    6.39   -2.11
16    17.0  225.0  126.0   99.0  4.0           13.10   16.21   -4.96

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
                Week                Day               Date Unnamed: 3_level_1
0                  1                Sun        September 9          1:00PM ET
1                  2                Sun       September 16          1:00PM ET
2                  3                Sun       September 23          1:00PM ET
3                  4                Sun       September 30          1:00PM ET
4                  5                Sun          October 7          1:00PM ET

  Unnamed: 4_level_0 Unnamed: 5_level_0 Unnamed: 6_level_0 Unnamed: 7_level_0  \
  Unnamed: 4_level_1 Unnamed: 5_level_1                 OT                Rec
0           boxscore                  L                NaN                0-1
1           boxscore                  L                NaN                0-2
2           boxscore                  W                NaN                1-2
3           boxscore                  L                NaN                1-3
4           boxscore                  W                NaN                2-3

  Unnamed: 8_level_0    Unnamed: 9_level_0 Score       Offense                \
  Unnamed: 8_level_1                   Opp    Tm   Opp    1stD  TotYd  PassY
0                  @      Baltimore Ravens   3.0  47.0    10.0  153.0   70.0
1                NaN  Los Angeles Chargers  20.0  31.0    17.0  293.0  209.0
2                  @     Minnesota Vikings  27.0   6.0    16.0  292.0  164.0
3                  @     Green Bay Packers   0.0  22.0    11.0  145.0   87.0
4                NaN      Tennessee Titans  13.0  12.0    18.0  223.0   79.0

              Defense                           Expected Points          \
   RushY   TO    1stD  TotYd  PassY  RushY   TO         Offense Defense
0   83.0  2.0    26.0  369.0  252.0  117.0  1.0          -28.71   -7.23
1   84.0  2.0    21.0  349.0  240.0  109.0  NaN           -1.04  -14.41
2  128.0  NaN    21.0  292.0  278.0   14.0  3.0            3.26   10.71
3   58.0  3.0    22.0  423.0  282.0  141.0  2.0          -21.05   -2.71
4  144.0  1.0    15.0  221.0  121.0  100.0  3.0           -2.83   12.22


  Sp. Tms
0   -2.33
1   -0.51
2    3.62
3    7.70
4   -8.39